wallpaper {
    monitor = eDP-1
    path = ~/.config/wallpaper/zenwritten_light_frame.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-1
    path = ~/.config/wallpaper/zenwritten_light_frame.jpg
    fit_mode = cover
}

#enable splash text rendering over the wallpaper
splash = false

ipc = on


